import { formatNumber, formatPaceLabel, sessionTheme } from './weeklyPlanShared';

function escapeIcsText(value) {
  return String(value || '')
    .replace(/\\/g, '\\\\')
    .replace(/\n/g, '\\n')
    .replace(/,/g, '\\,')
    .replace(/;/g, '\\;');
}

function pad2(n) {
  return String(n).padStart(2, '0');
}

/** Floating local datetime for ICS (no timezone suffix). */
export function toIcsLocalDateTime(date) {
  const d = new Date(date);
  if (Number.isNaN(d.getTime())) {
    return '';
  }
  return (
    `${d.getFullYear()}${pad2(d.getMonth() + 1)}${pad2(d.getDate())}` +
    `T${pad2(d.getHours())}${pad2(d.getMinutes())}${pad2(d.getSeconds())}`
  );
}

function toIcsUtcStamp(date = new Date()) {
  const d = new Date(date);
  return (
    `${d.getUTCFullYear()}${pad2(d.getUTCMonth() + 1)}${pad2(d.getUTCDate())}` +
    `T${pad2(d.getUTCHours())}${pad2(d.getUTCMinutes())}${pad2(d.getUTCSeconds())}Z`
  );
}

export function formatWorkoutText(day, { nextSessionDetail, scheduledDate } = {}) {
  const theme = sessionTheme(day?.sessionType);
  const lines = [];

  lines.push(day?.title || theme.label);
  lines.push(`Session type: ${theme.label}`);
  if (scheduledDate) {
    lines.push(`Date: ${scheduledDate.toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })}`);
  }
  if (day?.durationMinutes) {
    lines.push(`Duration: ${day.durationMinutes} min`);
  }
  if (day?.distanceKm) {
    lines.push(`Distance: ${formatNumber(day.distanceKm, { digits: 1, suffix: ' km' })}`);
  }
  if (day?.targetPace?.label) {
    lines.push(`Target pace: ${day.targetPace.label}`);
  } else if (day?.targetPace?.lowerMinPerKm && day?.targetPace?.upperMinPerKm) {
    lines.push(
      `Target pace: ${formatPaceLabel(day.targetPace.lowerMinPerKm)} – ${formatPaceLabel(day.targetPace.upperMinPerKm)}`
    );
  }
  if (day?.hrZone) {
    lines.push(`HR zone: ${day.hrZone}`);
  }
  if (day?.rpe) {
    lines.push(`RPE: ${day.rpe}`);
  }
  if (day?.description) {
    lines.push('');
    lines.push(day.description);
  }

  const blocks = nextSessionDetail
    ? ['warmup', 'mainSet', 'cooldown'].filter((key) => nextSessionDetail[key])
    : [];

  if (blocks.length) {
    lines.push('');
    lines.push('Session breakdown:');
    const labelMap = { warmup: 'Warm-up', mainSet: 'Main set', cooldown: 'Cool-down' };
    blocks.forEach((key) => {
      const block = nextSessionDetail[key];
      const blockLines = [`${labelMap[key]} (${block.durationMinutes || 0} min)`];
      if (block.description) {
        blockLines.push(block.description);
      }
      if (block.targetPace?.label) {
        blockLines.push(`Pace: ${block.targetPace.label}`);
      }
      if (block.hrZone) {
        blockLines.push(`HR: ${block.hrZone}`);
      }
      if (block.rpe) {
        blockLines.push(`RPE: ${block.rpe}`);
      }
      lines.push(blockLines.join(' — '));
    });
  }

  lines.push('');
  lines.push('Generated by RunAdvisor — not a Strava planned workout.');

  return lines.join('\n');
}

export function buildWorkoutIcs(day, { scheduledDate, dayIndex = 0, descriptionText } = {}) {
  const start = new Date(scheduledDate);
  const durationMin = Number(day?.durationMinutes) || 60;
  const end = new Date(start.getTime() + durationMin * 60 * 1000);
  const summary = day?.title || sessionTheme(day?.sessionType).label;
  const body = descriptionText || formatWorkoutText(day, { scheduledDate });
  const uid = `runadvisor-plan-${dayIndex}-${start.getTime()}@runadvisor.app`;

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//RunAdvisor//Weekly Plan//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    `UID:${uid}`,
    `DTSTAMP:${toIcsUtcStamp()}`,
    `DTSTART:${toIcsLocalDateTime(start)}`,
    `DTEND:${toIcsLocalDateTime(end)}`,
    `SUMMARY:${escapeIcsText(summary)}`,
    `DESCRIPTION:${escapeIcsText(body)}`,
    'END:VEVENT',
    'END:VCALENDAR',
    ''
  ].join('\r\n');
}

export function downloadIcsFile(icsContent, fileName) {
  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = fileName;
  anchor.click();
  URL.revokeObjectURL(url);
}
